@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
@TypeUseAreNonnullByDefault
package tamaized.datagenutil.assets.bakedmodel.block;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import tamaized.pkginfoutil.TypeUseAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;